complete -c magick -o adjoin -d 'Join images into a single multi-image file'
complete -c magick -o affine -d 'Affine transform matrix [matrix]'
complete -c magick -o antialias -d 'Remove pixel-aliasing'
complete -c magick -o authenticate -d 'Decipher image with this password [password]'
complete -c magick -o background -d 'Background color [color]' -xa '(__fish_complete_convert_options color)'
complete -c magick -o bias -d 'Add bias when convolving an image [value]'
complete -c magick -o black-point-compensation -d 'Use black point compensation'
complete -c magick -o blue-primary -d 'Chromaticity blue primary point [point]'
complete -c magick -o bordercolor -d 'Border color [color]' -xa '(__fish_complete_convert_options color)'
complete -c magick -o caption -d 'Assign a caption to an image [string]'
complete -c magick -o colors -d 'Preferred number of colors in the image [value]'
complete -c magick -o colorspace -d 'Alternate image colorspace [type]' -xa '(convert -list colorspace)'
complete -c magick -o comment -d 'Annotate image with comment [string]'
complete -c magick -o compose -d 'Set image composite operator [operator]'
complete -c magick -o compress -d 'Type of pixel compression when writing the image [type]' -xa '(convert -list compress)'
complete -c magick -o decipher -d 'magick cipher pixels to plain pixels'
complete -c magick -o define -d 'Define one or more image format options [format:option]'
complete -c magick -o delay -d 'Display the next image after pausing [value]'
complete -c magick -o density -d 'Horizontal and vertical density of the image [geometry]'
complete -c magick -o depth -d 'Image depth [value]'
complete -c magick -o direction -d 'Render text right-to-left or left-to-right [type]' -xa '(convert -list direction)'
complete -c magick -o display -d 'Get image or font from this X server [server]'
complete -c magick -o dispose -d 'Layer disposal method [method]' -xa '(convert -list dispose)'
complete -c magick -o dither -d 'Apply error diffusion to image [method]' -xa '(convert -list dither)'
complete -c magick -o encipher -d 'magick plain pixels to cipher pixels'
complete -c magick -o encoding -d 'Encoding type [type text]' -xa '(__fish_print_encodings)'
complete -c magick -o endian -d 'Endianness (MSB or LSB) of the image [type]' -xa '(convert -list endian)'
complete -c magick -o family -d 'Render text with this font family [name]' -xa '(__fish_complete_convert_options family)'
complete -c magick -o fill -d 'Color to use when filling a graphic primitive [color]' -xa '(__fish_complete_convert_options color)'
complete -c magick -o filter -d 'Use this filter when resizing an image [type]' -xa '(convert -list filter)'
complete -c magick -o flatten -d 'flatten a sequence of images'
complete -c magick -o font -d 'Render text with this font [name]' -xa '(__fish_complete_convert_options font)'
complete -c magick -o format -d 'Output formatted image characteristics ["string"]'
complete -c magick -o fuzz -d 'Colors within this distance are considered equal [distance]'
complete -c magick -o gravity -d 'Horizontal and vertical text placement [type]' -xa '(convert -list gravity)'
complete -c magick -o green-primary -d 'Chromaticity green primary point [point]'
complete -c magick -o intent -d 'Type of rendering intent when managing the image color [type]' -xa '(convert -list intent)'
complete -c magick -o interlace -d 'Type of image interlacing scheme [type]' -xa '(convert -list interlace)'
complete -c magick -o interpolate -d 'Pixel color interpolation method [method]' -xa '(convert -list interpolate)'
complete -c magick -o kerning -d 'Set the space between two letters [value]'
complete -c magick -o label -d 'Assign a label to an image [string]'
complete -c magick -o limit -d 'Pixel cache resource limit [type value]' -x
complete -c magick -o loop -d 'Add Netscape loop extension to your GIF animation [iterations]'
complete -c magick -o mask -d 'Associate a mask with the image [filename]' -r
complete -c magick -o matte -d 'store matte channel if the image has one'
complete -c magick -o mattecolor -d 'Frame color [color]' -xa '(__fish_complete_convert_options color)'
complete -c magick -o monitor -d 'Monitor progress'
complete -c magick -o orient -d 'Image orientation [type]' -xa '(convert -list orientation)'
complete -c magick -o origin -d 'image origin'
complete -c magick -o page -d 'Size and location of an image canvas (setting) [geometry]'
complete -c magick -o ping -d 'Efficiently determine image attributes'
complete -c magick -o pointsize -d 'Font point size [value]'
complete -c magick -o preview -d 'Image preview type [type]' -xa '(convert -list preview)'
complete -c magick -o quality -d 'JPEG/MIFF/PNG compression level [value]'
complete -c magick -o quiet -d 'Suppress all warning messages'
complete -c magick -o red-primary -d 'Chromaticity red primary point [point]'
complete -c magick -o regard-warnings -d 'Pay attention to warning messages'
complete -c magick -o repage -d 'size and location of an image canvas'
complete -c magick -o sampling-factor -d 'Horizontal and vertical sampling factor [geometry]'
complete -c magick -o scene -d 'Image scene number [value]'
complete -c magick -o seed -d 'Seed a new sequence of pseudo-random numbers [value]'
complete -c magick -o size -d 'Width and height of image [geometry]'
complete -c magick -o statistic -d 'replace pixels with corresponding stats from the neighborhood'
complete -c magick -o stretch -d 'Render text with this font stretch [type]' -xa '(convert -list stretch)'
complete -c magick -o stroke -d 'Graphic primitive stroke color [color]' -xa '(__fish_complete_convert_options color)'
complete -c magick -o strokewidth -d 'Graphic primitive stroke width [value]'
complete -c magick -o style -d 'Render text with this font style [type]' -xa '(convert -list style)'
complete -c magick -o support -d 'resize support: > 1.0 blurry, < 1.0 sharp'
complete -c magick -o synchronize -d 'Synchronize image to storage device'
complete -c magick -o taint -d 'Declare the image as modified'
complete -c magick -o texture -d 'Name of texture to tile onto the image background [filename]' -r
complete -c magick -o tile-offset -d 'Tile offset [geometry]'
complete -c magick -o treedepth -d 'Color tree depth [value]'
complete -c magick -o transparent-color -d 'Transparent color [color]' -xa '(__fish_complete_convert_options color)'
complete -c magick -o undercolor -d 'Annotation bounding box color [color]' -xa '(__fish_complete_convert_options color)'
complete -c magick -o units -d 'The units of image resolution [type]' -xa '(convert -list units)'
complete -c magick -o verbose -d 'Print detailed information about the image'
complete -c magick -o view -d 'FlashPix viewing transforms'
complete -c magick -o virtual-pixel -d 'Virtual pixel access method [method]' -xa '(convert -list virtual-pixel)'
complete -c magick -o weight -d 'Render text with this font weight [type]' -x
complete -c magick -o white-point -d 'Chromaticity white point [point]'
complete -c magick -o adaptive-blur -d 'Adaptively blur pixels; decrease effect near edges [geometry]'
complete -c magick -o adaptive-resize -d "Adaptively resize image using 'mesh' interpolation [geometry]"
complete -c magick -o adaptive-sharpen -d 'Adaptively sharpen pixels; increase effect near edges [geometry]'
complete -c magick -o annotate -d 'Annotate the image with text [geometry text]'
complete -c magick -o auto-orient -d 'Automagically orient (rotate) image'
complete -c magick -o bilateral-blur -d 'non-linear, edge-preserving, and noise-reducing smoothing filter'
complete -c magick -o black-threshold -d 'Force all pixels below the threshold into black [value]'
complete -c magick -o blue-shift -d 'Simulate a scene at nighttime in the moonlight [factor]'
complete -c magick -o blur -d 'Reduce image noise and reduce detail levels [geometry]'
complete -c magick -o border -d 'Surround image with a border of color [geometry]'
complete -c magick -o channel -d 'set the image channel mask'
complete -c magick -o charcoal -d 'Simulate a charcoal drawing [radius]'
complete -c magick -o chop -d 'Remove pixels from the image interior [geometry]'
complete -c magick -o clip -d 'Clip along the first path from the 8BIM profile'
complete -c magick -o clip-mask -d 'Associate a clip mask with the image [filename]' -r
complete -c magick -o clip-path -d 'Clip along a named path from the 8BIM profile [id]'
complete -c magick -o colorize -d 'Colorize the image with the fill color [value]'
complete -c magick -o color-matrix -d 'Apply color correction to the image [matrix]'
complete -c magick -o contrast -d 'Enhance or reduce the image contrast'
complete -c magick -o contrast-stretch -d 'Improve contrast by stretching the intensity range [geometry]'
complete -c magick -o convolve -d 'Apply a convolution kernel to the image [coefficients]'
complete -c magick -o cycle -d 'Cycle the image colormap [amount]'
complete -c magick -o despeckle -d 'Reduce the speckles within an image'
complete -c magick -o draw -d 'Annotate the image with a graphic primitive [string]'
complete -c magick -o edge -d 'Apply a filter to detect edges in the image [radius]'
complete -c magick -o emboss -d 'Emboss an image [radius]'
complete -c magick -o enhance -d 'Apply a digital filter to enhance a noisy image'
complete -c magick -o equalize -d 'Perform histogram equalization to an image'
complete -c magick -o evaluate -d 'Alter channel pixels based on expression [operator]'
complete -c magick -o extent -d 'Set the image size [geometry]'
complete -c magick -o extract -d 'Extract area from image [geometry]'
complete -c magick -o fft -d 'Implements the discrete Fourier transform (DFT)'
complete -c magick -o flip -d 'Flip image vertically'
complete -c magick -o floodfill -d 'Color floodfill the image with color [geometry]'
complete -c magick -o flop -d 'Flop image horizontally'
complete -c magick -o frame -d 'Surround image with an ornamental border [geometry]'
complete -c magick -o function -d 'Apply function over image values [name parameters]' -xa '(convert -list function)'
complete -c magick -o gamma -d 'Level of gamma correction [value]'
complete -c magick -o gaussian-blur -d 'Reduce image noise and reduce detail levels [geometry]'
complete -c magick -o geometry -d 'Preferred size or location of the image [geometry]'
complete -c magick -o identify -d 'Identify the format and characteristics of the image'
complete -c magick -o ift -d 'Implements the inverse discrete Fourier transform (DFT)'
complete -c magick -o implode -d 'Implode image pixels about the center [amount]'
complete -c magick -o integral -d 'calculate the sum of values (pixel values) in the image'
complete -c magick -o lat -d 'Local adaptive thresholding [geometry]'
complete -c magick -o layers -d 'Optimize, merge,  or compare image layers [method]' -xa '(convert -list layers)'
complete -c magick -o level -d 'Adjust the level of image contrast [value]'
complete -c magick -o linear-stretch -d 'Improve contrast by stretching with saturation [geometry]'
complete -c magick -o median -d 'Apply a median filter to the image [geometry]'
complete -c magick -o mode -d 'Make each pixel the predominant color of the neighborhood [geometry]'
complete -c magick -o modulate -d 'Vary the brightness, saturation, and hue [value]'
complete -c magick -o monochrome -d 'Transform image to black and white'
complete -c magick -o morphology -d 'Apply a morphology method to the image [method kernel]' -xa '(convert -list morphology)'
complete -c magick -o motion-blur -d 'Simulate motion blur [geometry]'
complete -c magick -o negate -d 'Replace every pixel with its complementary color '
complete -c magick -o noise -d 'Add or reduce noise in an image [geometry]'
complete -c magick -o normalize -d 'Transform image to span the full range of colors'
complete -c magick -o opaque -d 'Change this color to the fill color [color]' -xa '(__fish_complete_convert_options color)'
complete -c magick -o ordered-dither -d 'Add a noise pattern to the image with specific amplitudes  [NxN]'
complete -c magick -o paint -d 'Simulate an oil painting [radius]'
complete -c magick -o polaroid -d 'Simulate a Polaroid picture [angle]'
complete -c magick -o posterize -d 'Reduce the image to a limited number of color levels [levels]'
complete -c magick -o profile -d 'Add, delete, or apply an image profile [filename]' -r
complete -c magick -o quantize -d 'Reduce colors in this colorspace [colorspace]' -xa '(convert -list colorspace)'
complete -c magick -o radial-blur -d 'Radial blur the image [angle]'
complete -c magick -o raise -d 'Lighten/darken image edges to create a 3-D effect [value]'
complete -c magick -o random-threshold -d 'Random threshold the image [low,high]'
complete -c magick -o region -d 'Apply options to a portion of the image [geometry]'
complete -c magick -o render -d 'Render vector graphics'
complete -c magick -o resample -d 'Change the resolution of an image [geometry]'
complete -c magick -o resize -d 'Resize the image [geometry]'
complete -c magick -o roll -d 'Roll an image vertically or horizontally [geometry]'
complete -c magick -o rotate -d 'Apply Paeth rotation to the image [degrees]'
complete -c magick -o sample -d 'Scale image with pixel sampling [geometry]'
complete -c magick -o scale -d 'Scale the image [geometry]'
complete -c magick -o segment -d 'Segment an image [values]'
complete -c magick -o selective-blur -d 'Selectively blur pixels within a contrast threshold [geometry]'
complete -c magick -o sepia-tone -d 'Simulate a sepia-toned photo [threshold]'
complete -c magick -o set -d 'Set an image property [property value]'
complete -c magick -o shade -d 'Shade the image using a distant light source [degrees]'
complete -c magick -o shadow -d 'Simulate an image shadow [geometry]'
complete -c magick -o sharpen -d 'Sharpen the image [geometry]'
complete -c magick -o shave -d 'Shave pixels from the image edges [geometry]'
complete -c magick -o shear -d 'Slide one edge of the image along the X or Y axis [geometry]'
complete -c magick -o sigmoidal-contrast -d 'Lightness rescaling using sigmoidal contrast enhancement [geometry]'
complete -c magick -o sketch -d 'Simulate a pencil sketch [geometry]'
complete -c magick -o solarize -d 'Negate all pixels above the threshold level [threshold]'
complete -c magick -o sort-pixels -d 'sort each scanline in ascending order of intensity'
complete -c magick -o splice -d 'Splice the background color into the image [geometry]'
complete -c magick -o spread -d 'Displace image pixels by a random amount [radius]'
complete -c magick -o strip -d 'Strip image of all profiles and comments'
complete -c magick -o swirl -d 'Swirl image pixels about the center [degrees]'
complete -c magick -o threshold -d 'Threshold the image [value]'
complete -c magick -o thumbnail -d 'Create a thumbnail of the image [geometry]'
complete -c magick -o tile -d 'Tile image when filling a graphic primitive [filename]' -r
complete -c magick -o tint -d 'Tint the image with the fill color [value]'
complete -c magick -o transform -d 'Affine transform image'
complete -c magick -o transparent -d 'Make this color transparent within the image [color]' -xa '(__fish_complete_convert_options color)'
complete -c magick -o transpose -d 'Flip image vertically and rotate 90 degrees'
complete -c magick -o transverse -d 'Flop image horizontally and rotate 270 degrees'
complete -c magick -o trim -d 'Trim image edges'
complete -c magick -o type -d 'Image type [type]' -xa '(convert -list type)'
complete -c magick -o unique-colors -d 'Discard all but one of any pixel color'
complete -c magick -o unsharp -d 'Sharpen the image [geometry]'
complete -c magick -o vignette -d 'Soften the edges of the image in vignette style [geometry]'
complete -c magick -o wave -d 'Alter an image along a sine wave [geometry]'
complete -c magick -o white-threshold -d 'Force all pixels above the threshold into white [value]'
complete -c magick -o channel-extract -d 'extract the channels in order'
complete -c magick -o channel-inject -d 'inject the channels in order'
complete -c magick -o channel-swap -d 'swap the channels'
complete -c magick -o affinity -d 'transform image colors to match this set of colors'
complete -c magick -o append -d 'Append an image sequence'
complete -c magick -o clut -d 'Apply a color lookup table to the image'
complete -c magick -o coalesce -d 'Merge a sequence of images'
complete -c magick -o combine -d 'Combine a sequence of images'
complete -c magick -o composite -d 'Composite image'
complete -c magick -o crop -d 'Cut out a rectangular region of the image [geometry]'
complete -c magick -o deconstruct -d 'Break down an image sequence into constituent parts'
complete -c magick -o evaluate-sequence -d 'Alter channel pixels based on expression [operator]'
complete -c magick -o flatten -d 'Flatten a sequence of images'
complete -c magick -o fx -d 'Apply mathematical expression to an image channel(s) [expression]'
complete -c magick -o hald-clut -d 'Apply a Hald color lookup table to the image'
complete -c magick -o morph -d 'Morph an image sequence [value]'
complete -c magick -o mosaic -d 'Create a mosaic from an image sequence'
complete -c magick -o process -d 'Process the image with a custom image filter [arguments]' -xa '(convert -list filter)'
complete -c magick -o separate -d 'Separate an image channel into a grayscale image'
complete -c magick -o smush -d 'Smush an image sequence together [geometry]'
complete -c magick -o write -d 'Write images to this file [filename]' -r
complete -c magick -o clone -d 'Clone an image [indexes]'
complete -c magick -o delete -d 'Delete the image from the image sequence [indexes]'
complete -c magick -o duplicate -d 'Duplicate an image one or more times [count,indexes]'
complete -c magick -o insert -d 'Insert last image into the image sequence [index]'
complete -c magick -o swap -d 'Swap two images in the image sequence [indexes]'
complete -c magick -o debug -d 'Display copious debugging information [events]' -xa '(convert -list debug)'
complete -c magick -o help -d 'Print program options'
complete -c magick -o log -d 'Format of debugging information [format]' -xa '(__fish_complete_convert_options format)'
complete -c magick -o list -d 'Print a list of supported option arguments [type]' -xa '(convert -list list)'
complete -c magick -o version -d 'Print version information'